name: Download uno-check manifest

outputs:
  uno-check-manifest-json:
    value: ${{ steps.uno-check-manifest.outputs.manifest }}

runs:
  using: "composite"
  steps:
    - name: Update uno.check
      shell: pwsh
      run: $(dotnet tool update --global uno.check --add-source https://api.nuget.org/v3/index.json)
      
    - name: Find uno-check manifest uri
      id: uno-check-manifest-uri
      shell: pwsh
      run: |
          $uno_check_output=$(uno-check --ci --non-interactive --verbose --skip all) || $("Execution of the 'uno-check' utility completed with error #$($LASTEXITCODE)." | Write-Output)
          $regex="Loading Manifest from:\s*(\S+)"

          if ("$uno_check_output" -match $regex)
          {
            "manifest-uri=$($matches[1])" | Write-Output >> $env:GITHUB_OUTPUT 
          }
          else
          {
            "manifest-uri=${{ env.main-manifest-uri }}" | Write-Output >> $env:GITHUB_OUTPUT
          }

          $(exit 0)
      env:
        main-manifest-uri: https://raw.githubusercontent.com/unoplatform/uno.check/main/manifests/uno.ui.manifest.json

    - name: Download uno-check manifest
      id: uno-check-manifest
      shell: pwsh
      run: |
        $json = Invoke-WebRequest -uri '${{ env.uno-check-manifest-uri }}' | ConvertFrom-Json | ConvertTo-Json -Compress -Depth 10
        "manifest=$json" | Write-Output >> $env:GITHUB_OUTPUT
      env:
        uno-check-manifest-uri: ${{ steps.uno-check-manifest-uri.outputs.manifest-uri }}
