---

name: "Build"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  
jobs:

  uno-setup:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
            
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4.0.1
        with:
          global-json-file: global.json

      - name: Setup MSBuild
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0

      - name: Setup the Uno Platform
        uses: finebits/github-actions/devhub/uno-platform/setup@4a126d80a11c5fdc83ce884d3d23dffb30bc4495 # v2.0.0

      - name: Display dir '$env:TEMP'
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $dirs=$(ls $env:TEMP uno-check-* -Directory)
          echo $dirs

          $dirs | foreach { $(ls $_ -File) | foreach { echo "$_ content:"; cat $_ } }

      - name: Display .NET Information
        run: |
          dotnet --info

      - name: Display workload list
        run: |
          dotnet workload list

      - name: Build via msbuild
        if: runner.os == 'Windows'
        shell: pwsh
        run: msbuild -target:Rebuild -restore:True -verbosity:minimal -consoleLoggerParameters:Summary .\src\UnoBlankProject\UnoBlankProject.sln
