---

name: "Publish MacOS"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  
jobs:

  uno-setup:            
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4.0.1
        with:
          global-json-file: global.json

      - name: Setup the Uno Platform
        uses: finebits/github-actions/devhub/uno-platform/setup@4a126d80a11c5fdc83ce884d3d23dffb30bc4495 # v2.0.0

      - name: Switch Xcode
        run: sudo xcode-select -switch "/Applications/Xcode_16.1.app"

      - name: Publish maccatalyst app
        run: |
          mkdir -p "./publish/maccatalyst/app/"
          dotnet publish "./src/UnoBlankProject/UnoBlankProject/UnoBlankProject.csproj" --configuration=Release --framework=net9.0-maccatalyst --verbosity=minimal --nologo -p:CreatePackage=false -o "publish/maccatalyst/app"
          cp -r ./src/UnoBlankProject/UnoBlankProject/bin/Release/net9.0-maccatalyst/*.app  ./publish/maccatalyst/app

      - name: Publish maccatalyst pkg
        run: |
          mkdir -p "./publish/maccatalyst/pkg/"
          dotnet publish "./src/UnoBlankProject/UnoBlankProject/UnoBlankProject.csproj" --configuration=Release --framework=net9.0-maccatalyst --verbosity=minimal --nologo -p:CreatePackage=true -o "publish/maccatalyst/pkg"

      - name: Prepare desktop publish
        run: |
          dotnet build "./src/UnoBlankProject/UnoBlankProject/UnoBlankProject.csproj" --target:TargetFrameworks-Desktop --no-restore

      - name: Publish mac-desktop bin
        run: |
          mkdir -p "./publish/desktop/x64/bin/"
          dotnet publish "./src/UnoBlankProject/UnoBlankProject/UnoBlankProject.csproj" --configuration=Release --framework=net9.0-desktop --verbosity=minimal --nologo -p:SelfContained=true -o "publish/desktop/x64/bin" 

      - name: Publish mac-desktop app
        run: |
          mkdir -p "./publish/desktop/x64/app/"
          dotnet publish "./src/UnoBlankProject/UnoBlankProject/UnoBlankProject.csproj" --configuration=Release --framework=net9.0-desktop --verbosity=minimal --nologo -p:SelfContained=true -p:PackageFormat=app -o "publish/desktop/x64/app"

      - name: Publish mac-desktop pkg
        run: |
          mkdir -p "./publish/desktop/x64/pkg/"
          dotnet publish "./src/UnoBlankProject/UnoBlankProject/UnoBlankProject.csproj" --configuration=Release --framework=net9.0-desktop --verbosity=minimal --nologo -p:SelfContained=true -p:PackageFormat=pkg  -o "publish/desktop/x64/pkg"

      - name: Publish mac-desktop dmg
        run: |
          mkdir -p "./publish/desktop/x64/dmg/"
          dotnet publish "./src/UnoBlankProject/UnoBlankProject/UnoBlankProject.csproj" --configuration=Release --framework=net9.0-desktop --verbosity=minimal --nologo -p:SelfContained=true -p:PackageFormat=dmg  -o "publish/desktop/x64/dmg"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-packages
          path: ./publish
