---

name: "Publish MacOS"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  
jobs:

  uno-publish-macos:            
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4.0.1
        with:
          global-json-file: global.json

      - name: Setup the Uno Platform
        uses: finebits/github-actions/devhub/uno-platform/setup@4a126d80a11c5fdc83ce884d3d23dffb30bc4495 # v2.0.0

      - name: Switch Xcode
        run: sudo xcode-select -switch "/Applications/Xcode_16.1.app"

      - name: Publish maccatalyst app
        run: |
          mkdir -p "./publish/app/"
          dotnet publish --configuration=Release --framework=net9.0-maccatalyst --verbosity=minimal --nologo -p:CreatePackage=false -o "./publish/app" "./src/UnoBlankProject/UnoBlankProject/UnoBlankProject.csproj"

      - name: Publish maccatalyst pkg
        run: |
          mkdir -p "./publish/pkg/"
          dotnet publish --configuration=Release --framework=net9.0-maccatalyst --verbosity=minimal --nologo -p:CreatePackage=true -o "./publish/pkg" "./src/UnoBlankProject/UnoBlankProject/UnoBlankProject.csproj"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-packages
          path: ./publish
