---

name: "Uno setup"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  
jobs:

  uno-setup:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            workload-list: android ios maccatalyst macos maui
          - os: macos-latest
            workload-list: android ios maccatalyst macos
          - os: ubuntu-latest
            workload-list: android
            
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup .NET 8
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4.0.1
        with:
          dotnet-version: 8.x

      - name: Setup .NET 9
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4.0.1
        with:
          dotnet-version: 9.x

      - name: Info
        shell: bash
        run: |
          ls
          cat .\global.json
          dotnet workload --version

      - name: Install Workload 
        shell: bash
        run: |
          dotnet workload --version
          dotnet workload install ${{ matrix.workload-list }} --ignore-failed-sources --source "https://api.nuget.org/v3/index.json"

      - name: Setup the Uno Platform
        uses: finebits/github-actions/devhub/uno-platform/setup@4a126d80a11c5fdc83ce884d3d23dffb30bc4495 # v2.0.0
        with:
          uno-check-manifest: https://raw.githubusercontent.com/unoplatform/uno.check/95904fd037afa7714b695716dddfc5f4c2acf138/manifests/uno.ui.manifest.json  # "DOTNET_SDK_VERSION": "8.0.401"
