---

name: "Uno setup"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  
jobs:

  uno-setup:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            workload-list: android ios maccatalyst macos maui
          - os: macos-latest
            workload-list: android ios maccatalyst macos maui
          - os: ubuntu-latest
            workload-list: android maui-android
            
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Display Dir Information
        shell: pwsh
        run: |
          echo "temp: $env:TEMP"
          echo "tmp: $env:TMP"
          echo "user: $env:USERPROFILE"

      - name: Dir '$env:TEMP'
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ls $env:TEMP

      - name: Information
        shell: bash
        run: |
          echo "RUNNER_OS: $RUNNER_OS"
          echo "runner.os: ${{ runner.os}}"
          echo "runner.temp: ${{ runner.temp }}"

      - name: Setup .NET 8
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4.0.1
        with:
          dotnet-version: 8.x

      - name: Setup .NET 9
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4.0.1
        with:
          dotnet-version: 9.x

      - name: Setup .NET
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4.0.1
        with:
          global-json-file: global.json

      - name: Install Workload 
        shell: bash
        run: |
          dotnet workload --version
          dotnet workload config --update-mode
          dotnet workload install ${{ matrix.workload-list }} --source "https://api.nuget.org/v3/index.json"

      - name: Setup the Uno Platform
        uses: finebits/github-actions/devhub/uno-platform/setup@4a126d80a11c5fdc83ce884d3d23dffb30bc4495 # v2.0.0
        with:
          uno-check-manifest: https://raw.githubusercontent.com/unoplatform/uno.check/95904fd037afa7714b695716dddfc5f4c2acf138/manifests/uno.ui.manifest.json  # "DOTNET_SDK_VERSION": "8.0.401"

      - name: Dir '$env:TEMP'
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $dirs=$(ls $env:TEMP uno-check-* -Directory)
          echo $dirs

          $dirs | foreach { $(ls $_ -File) | foreach { echo "$_ content:"; cat $_ } }

      - name: Display .NET Information
        run: |
          dotnet --info
