---

name: uno.check

on:
  workflow_dispatch:
jobs:
  uno-check:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.x

      - uses: actions/setup-java@v4.3.0
        if: ${{ env.RUNNER_OS == 'linux' }}
        with:
          distribution: 'microsoft'
          java-version: 11

      - name: dotnet info
        shell: bash
        run: |
          dotnet --version
          dotnet --info

      - name: print env
        shell: bash
        run: printenv

      - name: update uno.check
        shell: bash
        run: dotnet tool install uno.check --global

      - name: list uno.check checkups
        shell: bash
        run: uno-check list

      - name: run uno.check
        shell: bash
        run: |
          uno-check --verbose --non-interactive --ci --fix \
                    --skip xcode --skip vswin --skip vsmac \
                    --skip windowshyperv --skip edgewebview2 --skip androidemulator --skip dotnetnewunotemplates
