---

name: uno.check

on:
  workflow_dispatch:
jobs:
  uno-check:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.x

      - name: dotnet info
        shell: bash
        run: |
          dotnet --version
          dotnet --info

      - name: print env
        shell: bash
        run: printenv

      - name: get AndroidSDK items
        shell: bash
        run: |
          echo "android home dir: $ANDROID_HOME"
          [ -d "$ANDROID_HOME/platform-tools" ] && ls -lAR "$ANDROID_HOME/platform-tools" || echo "::warning:: directory '$ANDROID_HOME/platform-tools' is missing"

      - name: check linux os
        id: is-linux
        shell: bash
        run: | 
          is_linux=$([ "$RUNNER_OS" == "Linux" ] && echo "true" || echo "false")
          echo "linux=$is_linux" >> $GITHUB_OUTPUT

      - name: update AndroidSDK
        if: ${{ steps.is-linux.outputs.linux == 'true' }}
        shell: bash
        run: |
          android list sdk -u

      - name: update uno.check
        shell: bash
        run: dotnet tool update uno.check --global

      - name: run uno.check
        shell: bash
        run: |
          uno-check --verbose --non-interactive --ci --fix --target all \
                    --skip vswin --skip vsmac --skip xcode --skip vswinworkloads --skip androidemulator --skip dotnetnewunotemplates
