---

name: uno.check

on:
  workflow_dispatch:
jobs:
  uno-check:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.x

      - name: dotnet info
        shell: bash
        run: |
          dotnet --version
          dotnet --info

      - name: print env
        shell: bash
        run: printenv

      - name: update uno.check
        shell: bash
        run: dotnet tool update uno.check --global

      - name: run uno.check
        shell: bash
        run: |
          uno-check --verbose --non-interactive --ci --fix --target all \
                    --skip vswin --skip vsmac --skip xcode --skip vswinworkloads --skip androidemulator --skip dotnetnewunotemplates
