---

name: uno.check

on:
  workflow_dispatch:
jobs:
  uno-check:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.x

      - uses: actions/setup-java@v4.3.0
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          distribution: 'microsoft'
          java-version: 11

      - name: dotnet info
        shell: bash
        run: |
          dotnet --version
          dotnet --info

      - name: print env
        shell: bash
        run: printenv

      - name: get AndroidSDK items
        shell: bash
        run: |
          echo "android home dir: $ANDROID_HOME"
          [ -d "$ANDROID_HOME/platform-tools" ] && echo "platform-tools - ok" || echo "::warning:: directory '$ANDROID_HOME/platform-tools' is missing"

      - name: update uno.check
        shell: bash
        run: dotnet tool update uno.check --global

      - name: run uno.check
        shell: bash
        run: |
          uno-check --verbose --non-interactive --ci --fix \
                    --skip xcode --skip vswin --skip vsmac --skip wsl --skip edgewebview2 --skip androidemulator
#                    --skip vswin --skip vsmac --skip xcode --skip vswinworkloads --skip androidemulator --skip dotnetnewunotemplates                    
